# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'HomeToGather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HomeToGather
  pod 'Firebase'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseStorage'
  pod 'FirebaseDynamicLinks'
end
